/**
 * Formal report narratives per agent — World Bank / Government report style.
 * Each entry maps an agent ID to a structured document narrative that is
 * rendered as the primary text body of the FullReportDocument component.
 * Charts and tables from outputData are embedded as referenced figures.
 */

export const REPORT_NARRATIVES = {

  /* ── Agent 01 · Programme Intelligence Orchestration ─── */
  a1: {
    docRef: 'PKSF-KHL-Q1-2026/ORCH/001',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This document records the orchestration plan generated by the Programme Intelligence system (Freya) for the Khulna Division Q1 2026 performance review cycle. The system processed a structured review request encompassing partner organisation (PO) performance assessment, loan portfolio analysis, field intelligence, beneficiary cohort welfare evaluation, compliance auditing, and the production of a board-ready advisory memorandum. All six required intent slots were confirmed with a confidence index of 0.94. A sequential specialist chain of eight agents was activated, with two mandatory human approval gates enforced in accordance with PKSF data governance protocols. The workflow completed within the defined constraints, producing a verified, board-ready artefact.`,
      },
      {
        heading: '1. Background and Context',
        body: `The Khulna Division is one of PKSF's priority geographic clusters under the ongoing World Bank-supported Inclusive Finance for Marginalised People (IFMP) project. As of Q1 2026, the division hosts twelve (12) active partner organisations collectively serving approximately 19,500 active borrowers. Routine quarterly performance reviews are a core accountability mechanism required under the PKSF–Partner Organisation financing agreements and the World Bank project's results monitoring framework.\n\nThe Programme Intelligence system automates the orchestration of multi-agent analytical workflows, replacing manual data aggregation with a governed, auditable pipeline. Each workflow activation is logged with a cryptographic chain of custody, ensuring traceability from raw MIS data to final board artefact.`,
      },
      {
        heading: '2. Workflow Design and Methodology',
        body: `The orchestration engine parsed the review request into six discrete intent slots: geographic scope (Khulna), reporting period (Q1 2026), deliverable class (regional performance memo), data perimeter (MIS and field tools only), compliance gate requirement (pre-release), and escalation authority (Deputy Director, Field Operations). All slots were confirmed before task decomposition commenced.\n\nThe specialist chain was structured to enforce data-dependency ordering: the PO roster (Agent 03) is always established before KPI computation (Agent 06), and field intelligence (Agent 04) is collected before beneficiary cohort analysis (Agent 05). Compliance review (Agent 08) was positioned as a mandatory gate preceding document drafting. Two human approval points were embedded: one at the compliance escalation stage and one at final artefact release.`,
      },
      {
        heading: '3. Specialist Chain Activated',
        body: `The following specialist agents were activated in the sequence illustrated in Figure 1 below. Agent 03 (PO Performance Monitor) established the denominator roster. Agent 06 (Loan Portfolio Health Analyst) computed KPIs and flagged statistical outliers. Agent 04 (Field Intelligence Analyst) contextualised outliers with ground-truth narrative. Agent 05 (Beneficiary Cohort Welfare Analyst) assessed household-level income stress. Agent 08 (Compliance & Policy Auditor) applied regulatory rules and triggered a mandatory human escalation. Following human approval, Agent 07 (Report Drafting Specialist) produced the board memorandum. Agent 02 (M&E Verification Specialist) verified PDO consistency. Agent 09 (Forecast & Risk Analyst) appended a forward-looking recovery projection.`,
      },
      {
        heading: '4. Governance and Compliance',
        body: `Two human approval gates were enforced during this workflow. The first was triggered by Agent 08 upon detecting a probable interest rate ceiling breach by Narikel MFI (PO-KHL-04), which exceeded the 27% flat-rate limit prescribed by the Bangladesh Bank MFI Regulations 2022 and PKSF Circular 2023-09. A mandatory hold was placed on the workflow, and the matter was escalated to the designated authorised officer. The second gate was the final artefact release review, which confirms that all PDO-level indicators are traceable and that no unverified data has been included in the board submission.\n\nNo autonomous disbursement actions, external API calls, or system modifications were initiated by the agent pipeline.`,
      },
      {
        heading: '5. Summary Assessment',
        body: `The orchestration pipeline executed successfully. All eight specialist agents completed their assigned tasks within the defined scope. Two partner organisations — PO-KHL-04 (Narikel MFI) and PO-KHL-09 (Shapla Credit) — were identified for focused review in the specialist reports. The workflow produced a fully verified, compliance-cleared board memorandum and an accompanying nine-quarter recovery forecast, both traceable to signed MIS extracts.`,
      },
    ],
  },

  /* ── Agent 03 · PO Performance Monitor ─────────────── */
  a3: {
    docRef: 'PKSF-KHL-Q1-2026/POM/003',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This report presents the findings of the Partner Organisation (PO) roster verification and preliminary performance assessment for Khulna Division, covering the period January to March 2026 (Q1 2026). A total of twelve (12) partner organisations were identified as active in the Khulna Division MIS core system. All organisations submitted the required quarterly data within the acceptable 14-day reporting window. No systemic data quality failures, null primary field officer assignments, or blocking integrity errors were detected. Two organisations — PO-KHL-04 (Narikel MFI) and PO-KHL-09 (Shapla Credit) — were flagged for follow-up review pending detailed KPI computation in the subsequent pipeline stage.`,
      },
      {
        heading: '1. Background and Context',
        body: `PKSF's quarterly performance monitoring framework requires that all active POs submit standardised MIS data within 14 days of each quarter's close. These submissions form the denominator basis for all KPI computations, including loan disbursement rates, repayment rates, and field officer performance ratios. Denominator integrity is a critical prerequisite: any inclusion of merged, dormant, or erroneously registered PO shells would produce systematically biased performance rankings.\n\nKhulna Division has been a priority zone under the PKSF–World Bank IFMP project since Q3 2023, reflecting its high concentration of economically vulnerable coastal communities, including those exposed to seasonal cyclone and flood risk. As of Q1 2026, the division accounts for approximately 8.2% of PKSF's total active borrower base.`,
      },
      {
        heading: '2. Data Sources and Methodology',
        body: `Primary data was extracted from the MIS core system using the signed ETL view po_quarterly, which provides immutable quarterly snapshots with MIS lineage identifiers. The use of this signed view, rather than raw table extracts, ensures auditability and prevents post-hoc manipulation of the denominator set. A denominator integrity check was performed prior to any KPI computation to confirm that all returned records correspond to currently registered, operationally active POs.\n\nThe integrity check applied three validation rules: (i) non-null primary field officer assignment; (ii) submission timestamp within the Q1 2026 reporting window; and (iii) active registration status confirmed against the PKSF Partner Registry as of 31 March 2026. All 12 records passed these checks.`,
      },
      {
        heading: '3. Findings',
        body: `Finding 3.1 — Complete Roster Coverage: All twelve (12) partner organisations registered as active in Khulna Division during Q1 2026 were successfully identified and verified in the MIS system. The roster spans organisations of varying scale, from small community-based microfinance entities to larger urban-adjacent POs.\n\nFinding 3.2 — Data Quality: No blocking data quality errors were detected in any of the 12 PO records. Zero records exhibited null primary field officer assignments, which is a prerequisite condition for valid KPI computation. This represents an improvement over Q4 2025, when two records required manual correction before processing could proceed.\n\nFinding 3.3 — Reporting Timeliness: All 12 POs submitted quarterly data within the 14-day reporting window. The maximum reporting gap observed was 9 days (PO-KHL-09, Shapla Credit), which falls within acceptable parameters. The median reporting gap was 4 days, consistent with the division-wide trend over the preceding four quarters.\n\nFinding 3.4 — Preliminary Flags: PO-KHL-04 (Narikel MFI) and PO-KHL-09 (Shapla Credit) have been flagged for detailed follow-up in the KPI and field intelligence pipeline stages, based on preliminary signals in the raw submission data (above-average client dropout entries and delayed field officer sign-off, respectively). These flags do not constitute adverse findings at this stage and will be resolved through subsequent analysis.`,
      },
      {
        heading: '4. Recommendations',
        body: `Recommendation 4.1: Proceed with KPI computation using the verified 12-PO roster as the canonical denominator for all Q1 2026 Khulna Division performance metrics.\n\nRecommendation 4.2: Route PO-KHL-04 and PO-KHL-09 for priority attention in the loan portfolio health and field intelligence stages, ensuring that available data is sufficient to support or refute the preliminary flags.\n\nRecommendation 4.3: Request an updated field officer assignment confirmation from PO-KHL-09 (Shapla Credit) prior to the Q2 2026 reporting cycle, to eliminate the risk of a null-officer integrity failure in the next quarter.\n\nRecommendation 4.4: Consider establishing an automated pre-submission data quality check accessible to POs, to further reduce the manual correction burden observed in previous quarters.`,
      },
      {
        heading: '5. Conclusion',
        body: `The Q1 2026 Khulna Division PO roster is complete, verified, and fit for use as the denominator in all subsequent KPI computations. The 12-PO dataset has been validated against three integrity criteria and passed without exception. Two organisations have been flagged for focused follow-up. The verified roster and associated MIS lineage identifiers are transmitted to the downstream pipeline stages as a signed, immutable reference.`,
      },
    ],
  },

  /* ── Agent 06 · Loan Portfolio Health Analyst ───────── */
  a6: {
    docRef: 'PKSF-KHL-Q1-2026/PFH/006',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This report presents the Q1 2026 loan portfolio health assessment for Khulna Division, based on the verified twelve-PO roster produced by Agent 03. The Khulna portfolio comprised 19,487 active loan accounts as of 31 March 2026, with total outstanding principal of BDT 847 million. The division-wide weighted repayment rate was 78.4%, representing a decline of 6.3 percentage points from the Q4 2025 baseline of 84.7%. Two partner organisations — PO-KHL-04 (Narikel MFI) and PO-KHL-09 (Shapla Credit) — were identified as statistical outliers through z-score analysis, with repayment rates of 64.2% and 61.8% respectively. These outliers were referred to the field intelligence stage for contextualisation.`,
      },
      {
        heading: '1. Background and Context',
        body: `Loan portfolio health is the primary performance dimension assessed under PKSF's quarterly review cycle. A healthy portfolio is characterised by repayment rates above the 80% threshold, a Portfolio at Risk (PAR) ratio below 5%, and a write-off rate consistent with historical baselines. Khulna Division's coastal geography exposes its borrower population to elevated climate and flood risk, which has historically produced greater quarter-to-quarter repayment volatility compared to inland divisions.\n\nThe Q1 2026 review period coincides with the aftermath of a moderate flooding event in three Khulna sub-districts (Dacope, Koyra, and Batiaghata) in late December 2025 and January 2026, which is expected to have affected borrower repayment capacity in those areas. This context was applied when interpreting outlier results.`,
      },
      {
        heading: '2. Data Sources and Methodology',
        body: `Portfolio data was extracted from the MIS loan ledger using signed views loan_portfolio_q and repayment_schedule_q for Q1 2026. KPIs were computed using the PKSF standard formulae: repayment rate = (total repayments received / total repayments due) × 100; PAR-30 = outstanding balance of accounts with payment overdue ≥ 30 days / total outstanding balance × 100; write-off rate = (write-offs in period / average portfolio balance) × annualised basis.\n\nOutlier detection applied a two-standard-deviation z-score threshold across the 12-PO cohort for each KPI. POs scoring below –2 SD on repayment rate or above +2 SD on PAR-30 were flagged as statistical outliers requiring contextualisation. Division-level aggregates were computed as weighted averages, weighted by each PO's share of active borrower count.`,
      },
      {
        heading: '3. Findings',
        body: `Finding 3.1 — Portfolio Scale: The Khulna portfolio of 19,487 active accounts (BDT 847M outstanding) represents a 4.2% increase in borrower count from Q4 2025, consistent with programme expansion targets under the IFMP project.\n\nFinding 3.2 — Repayment Rate Decline: The division-wide weighted repayment rate of 78.4% represents a statistically significant decline (p < 0.05) from the Q4 2025 baseline of 84.7%. The decline is concentrated in the three flood-affected sub-districts, which account for 7 of the 12 POs and approximately 63% of outstanding portfolio volume.\n\nFinding 3.3 — Statistical Outliers: PO-KHL-04 (Narikel MFI, repayment rate 64.2%) and PO-KHL-09 (Shapla Credit, repayment rate 61.8%) are the only two POs whose repayment rates fall below the –2 SD threshold of 66.1%. Both operate predominantly in Dacope and Koyra sub-districts, the areas of highest recorded flood impact. These results are consistent with, but not entirely explained by, the flood narrative; a field investigation is required.\n\nFinding 3.4 — PAR-30 and Write-Offs: The division-level PAR-30 ratio is 8.3%, exceeding the 5% PKSF threshold. PAR-30 for PO-KHL-04 is 17.6% and for PO-KHL-09 is 19.2%, both substantially above the divisional mean. Write-off rates remain within acceptable ranges (< 1%) for all POs, suggesting that the impairment is recent and potentially recoverable.`,
      },
      {
        heading: '4. Recommendations',
        body: `Recommendation 4.1: Commission an immediate field intelligence investigation of PO-KHL-04 and PO-KHL-09, focusing on borrower repayment capacity, field officer activity, and the correlation between flood exposure and loan account status.\n\nRecommendation 4.2: Initiate PAR-30 watch notifications to both flagged POs under PKSF Circular 2023-09, requiring monthly interim reporting until repayment rates return above the 75% threshold.\n\nRecommendation 4.3: Evaluate eligibility of PO-KHL-04 and PO-KHL-09 borrowers for the PKSF Disaster Recovery Facility, which provides restructured repayment schedules for accounts affected by declared climate events.\n\nRecommendation 4.4: Review the lending concentration of both flagged POs in Dacope and Koyra sub-districts against PKSF geographic risk diversification guidelines, with a view to recommending portfolio rebalancing in Q2 2026.`,
      },
      {
        heading: '5. Conclusion',
        body: `The Q1 2026 Khulna Division portfolio exhibits measurable stress, primarily driven by the late-2025 flooding event in three coastal sub-districts. Two partner organisations require immediate follow-up investigation. While the division-level repayment rate decline is significant, the low write-off rates and the identifiable geographic concentration of impaired accounts are positive indicators that the portfolio impact is contained and potentially recoverable, conditional on effective field intervention.`,
      },
    ],
  },

  /* ── Agent 04 · Field Intelligence Analyst ──────────── */
  a4: {
    docRef: 'PKSF-KHL-Q1-2026/FLD/004',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This report presents the findings of the field intelligence investigation conducted for Khulna Division Q1 2026, focusing on the two statistically outlying partner organisations identified in the portfolio health assessment: PO-KHL-04 (Narikel MFI) and PO-KHL-09 (Shapla Credit). Field evidence confirms that the repayment rate declines observed in both POs are primarily attributable to a flooding event that affected the Dacope and Koyra sub-districts in December 2025 and January 2026. Approximately 1,240 borrower households across both POs reported full or partial destruction of productive assets. This finding supports a humanitarian root-cause classification, which has material implications for the appropriate remediation pathway.`,
      },
      {
        heading: '1. Background and Context',
        body: `Following the statistical outlier identification in the portfolio health stage, PKSF protocol requires a field intelligence investigation before any adverse performance determination is recorded against a partner organisation. This requirement recognises that quantitative repayment data alone cannot distinguish between institutional underperformance and external shock-driven repayment incapacity.\n\nThe Dacope and Koyra sub-districts, where the majority of PO-KHL-04 and PO-KHL-09 borrowers reside, are classified as High Flood Risk Zone 2 under the Bangladesh Water Development Board's coastal zone risk atlas. Both sub-districts experienced significant inundation during the December 2025 event, estimated by the District Disaster Management Committee (DDMC) at 60–80% area coverage, affecting an estimated 4,200 households.`,
      },
      {
        heading: '2. Investigative Methodology',
        body: `Field intelligence was synthesised from four primary sources: (i) structured field officer reports submitted by PO-KHL-04 and PO-KHL-09 via the PKSF field reporting portal, covering 18 field officers and 312 focus group discussion records; (ii) satellite-derived flood extent data from the Bangladesh Space Research and Remote Sensing Organisation (SPARRSO) for December 2025; (iii) DDMC situation reports dated January 2026; and (iv) cross-referenced loan account-level geo-coded repayment data from the MIS to validate spatial correlation between flood extent and repayment failure.\n\nA causal attribution score was computed for each PO based on the proportion of non-performing accounts with a spatial overlay on the documented flood extent polygon. Accounts with a flood attribution score above 0.70 were classified as Climate-Attributed Non-Performing Loans (CANPL).`,
      },
      {
        heading: '3. Findings',
        body: `Finding 3.1 — Root Cause Confirmation: Field evidence strongly supports a humanitarian root-cause classification for the repayment decline in both flagged POs. The December 2025 flood event is the primary explanatory variable, accounting for an estimated 74% of the repayment shortfall in PO-KHL-04 and 81% in PO-KHL-09.\n\nFinding 3.2 — Asset Destruction Scale: Approximately 1,240 borrower households across both POs reported loss or significant damage to productive assets — primarily livestock, aquaculture pond stocks, and small business inventories — with an average reported asset loss of BDT 38,000 per household. This level of productive asset destruction is consistent with temporary incapacity to service loan obligations rather than unwillingness to repay.\n\nFinding 3.3 — Remaining Repayment Gap: After deducting flood-attributed accounts from the non-performing portfolio, the residual unexplained repayment shortfall is 4.1% for PO-KHL-04 and 2.7% for PO-KHL-09. These residuals warrant follow-up but do not indicate systemic institutional failure.\n\nFinding 3.4 — Field Officer Assessment: Field officer qualitative assessments characterise borrower sentiment as cooperative and intent to repay once productive capacity is restored. No reports of loan diversion, identity fraud, or deliberate repayment avoidance were recorded across the 312 focus group records reviewed.`,
      },
      {
        heading: '4. Recommendations',
        body: `Recommendation 4.1: Formally classify affected accounts in PO-KHL-04 and PO-KHL-09 as Climate-Attributed Non-Performing Loans (CANPL) in the MIS, in accordance with PKSF Circular 2024-03 (Climate-Resilient Lending Guidelines).\n\nRecommendation 4.2: Activate the PKSF Disaster Recovery Facility for eligible borrowers in both POs, providing a six-month moratorium on principal repayments and waiver of penalty interest for the affected period.\n\nRecommendation 4.3: Refer the residual unexplained shortfall (4.1% in PO-KHL-04, 2.7% in PO-KHL-09) to routine compliance monitoring in Q2 2026, rather than treating it as a Q1 adverse finding.\n\nRecommendation 4.4: Commission a climate-resilience audit of both POs' lending portfolios under the PKSF–World Bank IFMP project's Climate Risk Management Framework, to assess portfolio exposure to future flood events and recommend appropriate product-level risk mitigation.`,
      },
      {
        heading: '5. Conclusion',
        body: `The field intelligence investigation concludes that the repayment rate declines in PO-KHL-04 and PO-KHL-09 are primarily attributable to the December 2025 coastal flooding event rather than to institutional underperformance. The evidence base — drawing on field officer reports, satellite flood extent data, and MIS geo-coded repayment data — is sufficient to support a humanitarian root-cause classification. Appropriate remediation through the PKSF Disaster Recovery Facility is recommended, with residual shortfalls subject to routine Q2 monitoring.`,
      },
    ],
  },

  /* ── Agent 05 · Beneficiary Cohort Welfare Analyst ──── */
  a5: {
    docRef: 'PKSF-KHL-Q1-2026/BCW/005',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This report presents the beneficiary cohort welfare analysis for flood-affected borrowers of PO-KHL-04 (Narikel MFI) and PO-KHL-09 (Shapla Credit) in Khulna Division, Q1 2026. The analysis covers 1,240 households identified as experiencing productive asset loss in the field intelligence investigation. Welfare data confirms that 68% of the affected cohort has experienced income reduction of greater than 40% relative to the Q4 2025 baseline, meeting the PKSF threshold for classification as Income-Stressed Borrowers (ISB). The projected income recovery timeline, based on historical post-flood recovery data from comparable coastal divisions, is 9–14 months for households engaged in aquaculture and livestock (the primary livelihood activities in the affected area), suggesting that loan restructuring support will be required through Q3 2026 at minimum.`,
      },
      {
        heading: '1. Background and Context',
        body: `PKSF's beneficiary protection framework requires that welfare impacts on borrower cohorts be assessed whenever a humanitarian root cause has been confirmed for a repayment disruption event. This requirement reflects PKSF's mandate as a development finance institution with explicit social performance obligations, including those enshrined in the PKSF Social Performance Management Framework (SPMF, 2021) and the World Bank's Environmental and Social Standards (ESS) under the IFMP project.\n\nThe 1,240 affected households are spread across Dacope (710 households) and Koyra (530 households) sub-districts. The primary livelihood activities in these sub-districts are small-scale aquaculture (shrimp and fish farming, 42% of borrowers), livestock rearing (cattle and poultry, 31%), and petty trade and small enterprises (27%). All three activity types are associated with high asset vulnerability to flooding events.`,
      },
      {
        heading: '2. Methodology',
        body: `Welfare data was sourced from structured household surveys conducted by PO-KHL-04 and PO-KHL-09 field officers in February 2026, covering 887 of the 1,240 affected households (71.5% response rate). Survey data was supplemented with Bangladesh Bureau of Statistics (BBS) post-disaster income assessment data for Khulna District (January 2026) and validated against PKSF's SPMF progress-out-of-poverty index (PPI) scores recorded for borrowers at loan origination.\n\nIncome stress was defined as household income in Q1 2026 falling below 60% of the Q4 2025 baseline. Recovery timeline projections were derived from a parametric model calibrated on PKSF historical data from the 2022 Sylhet flood cohort and the 2023 Chittagong coastal flood cohort, adjusted for the geographic and livelihood characteristics of the Khulna cohort.`,
      },
      {
        heading: '3. Findings',
        body: `Finding 3.1 — Income Stress Prevalence: 68% of the affected cohort (approximately 843 households) experienced income reduction greater than 40% relative to Q4 2025 baseline, meeting the PKSF ISB classification threshold. Income stress is most severe among aquaculture-dependent households (81% ISB rate) due to the total loss of pond stocks, which have a longer regeneration cycle than other productive assets.\n\nFinding 3.2 — Asset Recovery Timeline: Parametric modelling projects a median income recovery timeline of 11.3 months for the affected cohort, with a 90th-percentile upper bound of 16 months. Aquaculture households face the longest recovery trajectory (median 13.5 months) due to the time required to restock and grow harvests to commercial yield. Livestock and petty trade households project shorter median recoveries of 8.2 and 6.7 months respectively.\n\nFinding 3.3 — Poverty Regression Risk: Approximately 18% of the ISB cohort (approximately 152 households) are classified as being at risk of falling below the national poverty line during the recovery period, based on PPI baseline scores and current income stress levels. This sub-cohort requires priority intervention.\n\nFinding 3.4 — Social Cohesion: No reports of community conflict, internal migration driven by debt distress, or loan repayment coercion by field officers were recorded in the welfare survey data.`,
      },
      {
        heading: '4. Recommendations',
        body: `Recommendation 4.1: Activate the PKSF Disaster Recovery Facility for all 1,240 affected households, providing a six-month principal repayment moratorium and waiver of penalty interest.\n\nRecommendation 4.2: Prioritise the 152 households at poverty regression risk for immediate referral to PKSF's social safety net linkage programme, which connects distressed borrowers with government cash transfer schemes (notably the Vulnerable Group Development programme and the National Social Security Strategy).\n\nRecommendation 4.3: Design a phased loan restructuring schedule for aquaculture-dependent households, with repayment commencement deferred to Q4 2026 to align with the projected harvest-cycle recovery timeline.\n\nRecommendation 4.4: Update PPI baseline scores for all 1,240 households in the SPMF tracker to reflect the post-shock welfare status, ensuring accurate social performance reporting to the World Bank under the IFMP project.`,
      },
      {
        heading: '5. Conclusion',
        body: `The beneficiary cohort welfare analysis confirms significant but recoverable income stress across the flood-affected borrower population of Khulna Division. The evidence supports a structured intervention response combining loan restructuring through the PKSF Disaster Recovery Facility, targeted social protection linkage for the highest-risk households, and differentiated recovery timelines by livelihood type. Sustained monitoring through Q3 2026 is recommended to track recovery progress and assess the need for additional support.`,
      },
    ],
  },

  /* ── Agent 08 · Compliance & Policy Auditor ─────────── */
  a8: {
    docRef: 'PKSF-KHL-Q1-2026/CPL/008',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This compliance audit report documents the findings of the policy and regulatory review conducted for Khulna Division's Q1 2026 partner organisation portfolio data, prior to the release of any board-level advisory artefact. The audit identified one probable regulatory violation: PO-KHL-04 (Narikel MFI) is assessed as likely exceeding the 27% flat interest rate ceiling prescribed by Bangladesh Bank MFI Regulations 2022 and PKSF Circular 2023-09. The effective interest rate computed from Q1 2026 loan disbursement and fee data is 31.4%, which exceeds the regulatory ceiling by 4.4 percentage points. In accordance with PKSF escalation protocols, a mandatory human review gate has been triggered and workflow has been suspended pending authorised officer determination.`,
      },
      {
        heading: '1. Regulatory Framework',
        body: `PKSF partner organisations are subject to a multi-layered compliance framework comprising: (i) Bangladesh Bank MFI Regulations 2022, which establish the national regulatory floor for microfinance operations, including the 27% flat interest rate ceiling and mandatory client protection disclosures; (ii) PKSF Operational Guidelines 2020 (revised 2024), which extend PKSF-specific requirements including geographic diversification, social performance reporting, and field officer conduct standards; (iii) PKSF Circular 2023-09 (Governance and Compliance Strengthening), which mandates real-time interest rate monitoring and establishes the escalation protocol applied in this case.\n\nThe Programme Intelligence compliance audit engine is configured to apply all three layers to each quarterly data submission, generating a compliance determination for each applicable rule before any performance data is transmitted to the board reporting stage.`,
      },
      {
        heading: '2. Audit Methodology',
        body: `Compliance checks were applied to all 12 PO submissions using rule engine version 2.3.1, which encodes 47 distinct rule conditions across the three regulatory layers. Rules were applied in order of severity: blocking violations (which halt the workflow pending human review), advisory violations (which are flagged in the report but do not halt the workflow), and informational notices.\n\nThe effective interest rate for each PO was computed using the declining balance method, incorporating all fee income recorded in the Q1 2026 MIS disbursement data. This methodology is consistent with the Bangladesh Bank's prescribed effective rate calculation approach and PKSF's internal audit standards. The computation was repeated using two additional methodologies (flat rate and internal rate of return) to provide cross-validation.`,
      },
      {
        heading: '3. Findings',
        body: `Finding 3.1 — Interest Rate Ceiling Breach (Blocking): PO-KHL-04 (Narikel MFI) recorded a computed effective interest rate of 31.4% in Q1 2026, against a regulatory ceiling of 27%. The excess of 4.4 percentage points was confirmed using all three computation methodologies, eliminating calculation methodology as an explanatory factor. This finding constitutes a probable blocking violation under Bangladesh Bank MFI Regulations 2022 and PKSF Circular 2023-09, triggering the mandatory human review gate.\n\nFinding 3.2 — Advisory Notices (Non-Blocking): Three advisory notices were recorded for the Khulna portfolio: (i) PO-KHL-09 submitted its Q1 data 9 days after quarter close, which is within the 14-day window but above the 5-day target; (ii) two POs have field officer caseloads above the PKSF recommended maximum of 150 active borrowers per officer; (iii) social performance reporting completeness for the flood-affected cohort was 71.5%, below the 80% target.\n\nFinding 3.3 — Rule Engine Coverage: All 47 rule conditions were successfully evaluated for all 12 POs. No data gaps prevented rule application. The audit provides complete coverage of the Q1 2026 Khulna portfolio.`,
      },
      {
        heading: '4. Escalation Action Required',
        body: `The probable interest rate breach by PO-KHL-04 requires a determination by an authorised officer before the workflow can proceed. The authorised officer must determine: (i) whether the computed rate is confirmed as a regulatory violation, based on review of PO-KHL-04's fee disclosure documentation; (ii) if confirmed, whether the matter should be referred to Bangladesh Bank for regulatory enforcement action; (iii) the appropriate remedial conditions to be imposed on PO-KHL-04 as a condition of continued PKSF financing.\n\nWorkflow resumption and board memorandum drafting will proceed only upon receipt of a signed authorised officer determination.`,
      },
      {
        heading: '5. Recommendations',
        body: `Recommendation 5.1: Conduct an immediate desk review of PO-KHL-04's fee disclosure documentation for Q1 2026, and determine whether the computed 31.4% effective rate is confirmed as a regulatory violation.\n\nRecommendation 5.2: If the violation is confirmed, initiate a Bangladesh Bank notification under Section 14 of the MFI Regulations 2022, and place PO-KHL-04 on a PKSF Performance Improvement Plan (PIP) with quarterly monitoring.\n\nRecommendation 5.3: Issue advisory guidance to the two POs with over-loaded field officer caseloads, requesting a recruitment plan for additional officers within 60 days.\n\nRecommendation 5.4: Require PO-KHL-04, PO-KHL-09, and any other POs below the 80% social performance reporting completeness target to submit supplementary reporting within 30 days.`,
      },
      {
        heading: '6. Conclusion',
        body: `The Q1 2026 Khulna Division compliance audit has identified one probable blocking violation requiring human determination before the workflow can proceed. The interest rate ceiling issue at PO-KHL-04 is a material regulatory matter that must be resolved in the board memorandum. The three advisory notices are manageable through standard supervisory processes. Upon receipt of the authorised officer determination, the compliance engine will clear the workflow for document drafting.`,
      },
    ],
  },

  /* ── Agent 07 · Report Drafting Specialist ──────────── */
  a7: {
    docRef: 'PKSF-KHL-Q1-2026/MEMO/007',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This report documents the production of the Q1 2026 Khulna Division Performance Review Board Memorandum (Ref: PKSF/PI/KHL/Q1-2026/MEMO/007). The memorandum synthesises findings from all upstream specialist pipeline stages — portfolio health, field intelligence, beneficiary welfare, and compliance audit — into a single board-ready advisory document. The document was drafted in accordance with PKSF board communication standards (Document Standards Manual, 2023 edition) and has been structured to support executive-level decision-making without requiring reference to the full specialist reports.\n\nThe memorandum is classified as Internal — PKSF Use Only and has been designated for transmission to the PKSF Board of Governors Agenda Pack for the Q2 2026 session.`,
      },
      {
        heading: '1. Drafting Mandate and Scope',
        body: `The Report Drafting Specialist received a confirmed workflow release following the authorised officer's determination on the PO-KHL-04 interest rate matter, and a synthesis instruction covering all seven upstream findings. The drafting mandate required: (i) faithful representation of all material findings without editorial suppression; (ii) structuring of the compliance escalation as a mandatory agenda item requiring board-level resolution; (iii) integration of the recovery forecast produced by Agent 09 as a forward-looking context section; and (iv) clear delineation of recommendations by responsible party and implementation timeline.`,
      },
      {
        heading: '2. Document Structure',
        body: `The board memorandum was structured in six sections as per PKSF board document standards:\n\n1. Situation Overview: A concise narrative of the Khulna Division Q1 2026 operational context, including the December 2025 flood event and its portfolio implications.\n\n2. Portfolio Performance Summary: Division-level KPIs with year-on-year and quarter-on-quarter trend data, presented in the PKSF standard performance scorecard format.\n\n3. Partner Organisation Spotlight: Detailed findings for PO-KHL-04 and PO-KHL-09, including root cause analysis and welfare impact assessment.\n\n4. Compliance Matter for Board Resolution: The PO-KHL-04 interest rate ceiling issue, presented as a mandatory agenda item.\n\n5. Recovery Outlook: The nine-quarter forecast produced by Agent 09, contextualising the expected recovery trajectory under base case and adverse scenarios.\n\n6. Recommended Board Actions: A consolidated action list, with responsible party, timeline, and resource implications.`,
      },
      {
        heading: '3. Quality Assurance',
        body: `All quantitative claims in the memorandum were sourced directly from the signed MIS extracts produced by upstream agents. No manual data entry was used in the production of the document. The M&E Verification Specialist (Agent 02) independently verified all PDO-level indicators cited in the document against the PKSF Results Framework and the World Bank IFMP project's designated data sources.\n\nThe document was checked against the PKSF Document Standards Manual for formatting, nomenclature, and classification markings. All acronyms are expanded at first use. The document does not contain forward-looking projections without explicit source attribution to the Agent 09 forecast model.`,
      },
      {
        heading: '4. Conclusion',
        body: `The Q1 2026 Khulna Division Performance Review Board Memorandum has been produced in full compliance with PKSF board communication standards. The document is transmission-ready, pending M&E verification clearance. All findings, recommendations, and compliance matters have been accurately represented and are fully traceable to the upstream agent pipeline outputs through the MIS lineage identifiers recorded in the document metadata.`,
      },
    ],
  },

  /* ── Agent 02 · M&E Verification Specialist ─────────── */
  a2: {
    docRef: 'PKSF-KHL-Q1-2026/MEV/002',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This report presents the results of the M&E verification check conducted on the Q1 2026 Khulna Division Board Memorandum, prior to its formal transmission. The verification assessed the consistency of all Programme Development Objective (PDO) indicators cited in the memorandum against the designated data sources specified in the PKSF Results Framework and the World Bank IFMP project's Project Operations Manual (POM). All seven PDO-level indicators cited in the memorandum were verified and confirmed as consistent with their designated data sources. No material discrepancies were identified. The memorandum is cleared for board transmission.`,
      },
      {
        heading: '1. Verification Mandate',
        body: `Under the World Bank IFMP project's fiduciary and results management protocols, all documents citing PDO-level indicators must undergo independent M&E verification before transmission to the board or to World Bank supervision teams. This requirement is designed to prevent misrepresentation of project results, whether through data entry error, source substitution, or methodological inconsistency.\n\nThe M&E Verification Specialist operates as an independent check within the Programme Intelligence pipeline, with no access to the upstream agents' working data until the board memorandum is presented for verification. This structural independence ensures that the verification is not circular.`,
      },
      {
        heading: '2. Verification Methodology',
        body: `Each PDO indicator cited in the memorandum was verified against four criteria: (i) source consistency — the data source cited in the memorandum matches the designated source specified in the POM; (ii) computational accuracy — the figure cited is consistent with the formula and denominator prescribed in the Results Framework indicator sheet; (iii) period coverage — the data reflects the Q1 2026 reporting period (1 January to 31 March 2026) as defined in the project's annual work plan; and (iv) disaggregation completeness — where the indicator requires disaggregation by sex or poverty status, the disaggregated data is present and correctly aggregated to the headline figure.\n\nVerification was performed using direct access to the signed MIS extracts and the PKSF Results Framework database, independent of the pipeline agents' working files.`,
      },
      {
        heading: '3. Findings',
        body: `Finding 3.1 — Active Borrower Count (PDO-1): The memorandum cites 19,487 active borrowers in Khulna Division as of Q1 2026. This figure was verified against the MIS loan ledger signed extract. Confirmed as accurate.\n\nFinding 3.2 — Repayment Rate (PDO-2): The memorandum cites a weighted average repayment rate of 78.4%. Verified against the repayment_schedule_q signed view using the PKSF standard formula. Confirmed as accurate.\n\nFinding 3.3 — Female Borrower Share (PDO-3): The memorandum cites 94.2% female beneficiary share. Verified against MIS borrower demographic data. Confirmed as accurate and consistent with the Results Framework requirement for ≥ 90% female share.\n\nFinding 3.4 — Poverty-Targeted Borrower Share (PDO-4): The memorandum cites 61.8% of borrowers below the national poverty line at loan origination. Verified against PPI baseline scores in the SPMF tracker. Confirmed as accurate.\n\nFinding 3.5 — Field Officer Visits (PDO-5 through PDO-7): All three operational indicators verified and confirmed consistent with designated MIS data sources.\n\nFinding 3.6 — No Discrepancies: No material discrepancies were identified between the memorandum figures and the verified data sources. One rounding difference of 0.1 percentage points was observed in PDO-2 (78.4% vs 78.38% unrounded); this is within acceptable rounding conventions and does not constitute a discrepancy.`,
      },
      {
        heading: '4. Verification Determination',
        body: `All seven PDO-level indicators in the Q1 2026 Khulna Division Board Memorandum are verified as consistent with their designated data sources, correctly computed, and appropriately disaggregated. The memorandum is cleared for board transmission and for inclusion in the Q1 2026 World Bank Supervision Mission data pack.\n\nThis verification clearance is recorded in the PKSF M&E Verification Register under reference PKSF/MEV/KHL/Q1-2026/002 and is auditable by the World Bank supervision team.`,
      },
      {
        heading: '5. Conclusion',
        body: `The M&E verification of the Q1 2026 Khulna Division Board Memorandum is complete. All PDO indicators have been independently verified and cleared. The document is transmission-ready. The verification record is logged in the PKSF M&E Verification Register with full source traceability.`,
      },
    ],
  },

  /* ── Agent 09 · Forecast & Risk Analyst ─────────────── */
  a9: {
    docRef: 'PKSF-KHL-Q1-2026/FCT/009',
    sections: [
      {
        heading: 'Executive Summary',
        body: `This report presents the forward-looking portfolio recovery forecast for Khulna Division, covering nine quarters from Q2 2026 to Q2 2028, prepared as a supporting annex to the Q1 2026 Board Memorandum. The forecast is anchored to the Q1 2026 division-wide repayment rate of 78.4% and projects a base case recovery to the 84–85% range by Q2 2027, consistent with the pre-flood Q4 2025 baseline of 84.7%. The forecast is derived from a parametric model calibrated on PKSF post-disaster recovery data from comparable coastal flood events in 2022 and 2023. An adverse scenario — reflecting a hypothetical recurrence of coastal flooding in Q3 2026 — projects a more protracted recovery to Q4 2027. The base case is assessed as the more probable outcome absent a further climate event.`,
      },
      {
        heading: '1. Forecasting Mandate and Scope',
        body: `The forecast was commissioned as a mandatory component of the board memorandum package, in accordance with PKSF's updated board reporting standards (Circular 2024-07), which require all performance reviews involving a humanitarian root-cause determination to include a forward-looking recovery trajectory. The mandate scope covers the Khulna Division aggregate repayment rate; PO-level forecasts for PO-KHL-04 and PO-KHL-09 are also provided as supporting detail.\n\nThe forecast covers nine quarters (Q2 2026 to Q2 2028), which encompasses the projected recovery period for the affected beneficiary cohort as estimated in the welfare analysis (median 11.3 months, 90th percentile 16 months). The forecast period is deliberately extended to Q2 2028 to provide the board with sufficient forward visibility for medium-term resource planning.`,
      },
      {
        heading: '2. Forecasting Methodology',
        body: `The forecast model is a parametric recovery curve fitted to PKSF historical data from two comparable post-flood events: the 2022 Sylhet flood (which affected 14 POs and produced a 9.2 percentage point repayment rate decline) and the 2023 Chittagong coastal flood (11 POs, 7.6 percentage point decline). Both events followed a consistent recovery trajectory characterised by a rapid stabilisation phase in the first two quarters, a moderate recovery phase over quarters 3–5, and a plateau phase from quarter 6 onwards.\n\nThe Khulna event is parameterised as a 6.3 percentage point decline from the Q4 2025 baseline, which is within the range of the two calibration events. The base case recovery curve applies the mean recovery rate from the calibration dataset, adjusted for two Khulna-specific factors: (i) the higher proportion of aquaculture-dependent borrowers, which lengthens the recovery tail; and (ii) the activation of the PKSF Disaster Recovery Facility, which the historical data indicates accelerates recovery by approximately 1.5 quarters on average.`,
      },
      {
        heading: '3. Forecast Results',
        body: `Base Case (Figure 1 in supporting data): The division-wide repayment rate is forecast to recover from 78.4% (Q1 2026) to approximately 81% by Q4 2026, 83% by Q2 2027, and 84–85% (consistent with the pre-flood baseline) by Q3 2027. The model projects stabilisation at or above 85% from Q4 2027, assuming no further climate shocks and effective implementation of the Disaster Recovery Facility for the affected cohort.\n\nAdverse Scenario: In the event of a further coastal flooding event in Q3 2026 — consistent with the historical recurrence frequency of 0.35 events per year in High Flood Risk Zone 2 — the recovery trajectory would be materially delayed, with the baseline repayment rate not reached until Q1 2028. This scenario underscores the importance of climate risk mitigation measures recommended in the field intelligence report.\n\nPO-Level Projections: PO-KHL-04 and PO-KHL-09 are individually forecast to recover to the 75% repayment rate threshold (the minimum required to exit PAR-30 watch status) by Q3 2026 under the base case, and by Q4 2026 under the adverse scenario. Full recovery to pre-flood performance levels is projected by Q2 2027 for both POs under the base case.`,
      },
      {
        heading: '4. Risk Factors and Uncertainties',
        body: `The forecast is subject to four principal uncertainties: (i) Climate recurrence risk — the most material uncertainty, given the historical flood frequency in the affected sub-districts and the increasing volatility of the Bay of Bengal weather system associated with climate change; (ii) Disaster Recovery Facility uptake — the recovery acceleration attributed to the facility assumes full eligible borrower uptake; lower uptake would reduce the acceleration effect; (iii) Macro-economic conditions — significant changes in agricultural commodity prices, particularly shrimp and fish prices, would affect aquaculture-dependent borrower income recovery; and (iv) PO-KHL-04 regulatory situation — the pending resolution of the interest rate compliance matter introduces operational uncertainty that could affect PO-KHL-04's client base and field officer retention.`,
      },
      {
        heading: '5. Recommendations',
        body: `Recommendation 5.1: Adopt the base case forecast as the planning baseline for Q2 2026 board reporting, with explicit acknowledgement of the adverse scenario risk.\n\nRecommendation 5.2: Commission an independent climate risk assessment of the Khulna Division portfolio under the PKSF–World Bank IFMP project's Climate Risk Management Framework, to quantify the probability and impact of future flood events on portfolio performance.\n\nRecommendation 5.3: Establish a quarterly tracking dashboard for the recovery trajectory, with automatic alert generation if the observed repayment rate falls more than 2 percentage points below the base case forecast in any given quarter.\n\nRecommendation 5.4: Incorporate climate resilience performance metrics into the PO financing agreements for PO-KHL-04 and PO-KHL-09, to create incentives for climate-adaptive lending practices.`,
      },
      {
        heading: '6. Conclusion',
        body: `The Q1 2026 Khulna Division portfolio recovery forecast projects a return to pre-flood performance levels by Q3 2027 under the base case, subject to the effective activation of the PKSF Disaster Recovery Facility and the absence of further major climate events. The adverse scenario, while feasible, is not the central projection. The forecast provides the board with a quantified, calibrated view of the recovery trajectory and the associated risk factors, supporting informed resource allocation and supervisory decision-making for the Q2 2026–Q2 2027 period.`,
      },
    ],
  },

};
